import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar'
import MyDP from './components/MyDP'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Sarthak's Profile",
  description: 'Generated by Sarthak Mishra',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="dark:bg-slate-800">
        <Navbar />
        <MyDP />
        {children}
        </body>
    </html>
  )
}
